apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autotune-cr
rules:
- apiGroups:
  - recommender.com
  resources:
  - autotunes
  - autotuneconfigs
  - autotunequeryvariables
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
